/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface IonApp {}
  interface IonAppAttributes extends StencilHTMLAttributes {}

  interface IonBuy {}
  interface IonBuyAttributes extends StencilHTMLAttributes {
    'onNavigate'?: (event: CustomEvent) => void;
  }

  interface IonHome {}
  interface IonHomeAttributes extends StencilHTMLAttributes {
    'onGiveFlips'?: (event: CustomEvent) => void;
    'onNavigate'?: (event: CustomEvent) => void;
  }

  interface IonLogin {}
  interface IonLoginAttributes extends StencilHTMLAttributes {
    'onNavigate'?: (event: CustomEvent) => void;
  }

  interface IonOnboarding2 {}
  interface IonOnboarding2Attributes extends StencilHTMLAttributes {
    'onNavigate'?: (event: CustomEvent) => void;
  }

  interface IonOnboarding3 {}
  interface IonOnboarding3Attributes extends StencilHTMLAttributes {
    'onNavigate'?: (event: CustomEvent) => void;
  }

  interface IonOnboarding {}
  interface IonOnboardingAttributes extends StencilHTMLAttributes {
    'onNavigate'?: (event: CustomEvent) => void;
  }

  interface IonPhone {}
  interface IonPhoneAttributes extends StencilHTMLAttributes {
    'onNavigate'?: (event: CustomEvent) => void;
  }

  interface IonProfile {}
  interface IonProfileAttributes extends StencilHTMLAttributes {
    'onNavigate'?: (event: CustomEvent) => void;
  }

  interface IonRouter {}
  interface IonRouterAttributes extends StencilHTMLAttributes {
    'onDashboardColor'?: (event: CustomEvent) => void;
    'onNavigate'?: (event: CustomEvent) => void;
  }

  interface IonSignup {}
  interface IonSignupAttributes extends StencilHTMLAttributes {
    'onNavigate'?: (event: CustomEvent) => void;
  }

  interface IonTypes {}
  interface IonTypesAttributes extends StencilHTMLAttributes {
    'onNavigate'?: (event: CustomEvent) => void;
  }

  interface IonValidationCode {}
  interface IonValidationCodeAttributes extends StencilHTMLAttributes {
    'onNavigate'?: (event: CustomEvent) => void;
  }

  interface IonValidationCompleted {}
  interface IonValidationCompletedAttributes extends StencilHTMLAttributes {
    'onNavigate'?: (event: CustomEvent) => void;
    'onWallet'?: (event: CustomEvent) => void;
  }

  interface IonLateralDashboard {
    'closeIconFill': string;
    'dashboardHide': boolean;
    'profileGradient': string;
  }
  interface IonLateralDashboardAttributes extends StencilHTMLAttributes {
    'closeIconFill'?: string;
    'dashboardHide'?: boolean;
    'onDashboardHandler'?: (event: CustomEvent) => void;
    'onNavigate'?: (event: CustomEvent) => void;
    'profileGradient'?: string;
  }

  interface IonCallToAction {}
  interface IonCallToActionAttributes extends StencilHTMLAttributes {
    'onCallToActionHide'?: (event: CustomEvent) => void;
  }

  interface IonOpenButton {
    'buttonHide': boolean;
  }
  interface IonOpenButtonAttributes extends StencilHTMLAttributes {
    'buttonHide'?: boolean;
    'onButtonHandler'?: (event: CustomEvent) => void;
  }

  interface IonArrow {
    'arrowUp': boolean;
  }
  interface IonArrowAttributes extends StencilHTMLAttributes {
    'arrowUp'?: boolean;
  }

  interface IonHeader {}
  interface IonHeaderAttributes extends StencilHTMLAttributes {
    'onNavigate'?: (event: CustomEvent) => void;
  }

  interface IonLogout {
    'action': any;
    'backgroundColor': string;
    'color': string;
    'logoutColor': string;
  }
  interface IonLogoutAttributes extends StencilHTMLAttributes {
    'action'?: any;
    'backgroundColor'?: string;
    'color'?: string;
    'logoutColor'?: string;
    'onNavigate'?: (event: CustomEvent) => void;
  }

  interface IonConfirm {}
  interface IonConfirmAttributes extends StencilHTMLAttributes {}

  interface IonInputRange {}
  interface IonInputRangeAttributes extends StencilHTMLAttributes {
    'onRangeEmitter'?: (event: CustomEvent) => void;
  }

  interface IonMessage {
    'confirmation': boolean;
    'error': boolean;
    'flips': number;
  }
  interface IonMessageAttributes extends StencilHTMLAttributes {
    'confirmation'?: boolean;
    'error'?: boolean;
    'flips'?: number;
  }

  interface IonNumber {
    'range': number;
  }
  interface IonNumberAttributes extends StencilHTMLAttributes {
    'range'?: number;
  }

  interface IonSlider {
    'initialBalance': number;
    'sliderHide': boolean;
  }
  interface IonSliderAttributes extends StencilHTMLAttributes {
    'initialBalance'?: number;
    'onButtonHandler'?: (event: CustomEvent) => void;
    'onDashboardHandler'?: (event: CustomEvent) => void;
    'sliderHide'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'IonApp': Components.IonApp;
    'IonBuy': Components.IonBuy;
    'IonHome': Components.IonHome;
    'IonLogin': Components.IonLogin;
    'IonOnboarding2': Components.IonOnboarding2;
    'IonOnboarding3': Components.IonOnboarding3;
    'IonOnboarding': Components.IonOnboarding;
    'IonPhone': Components.IonPhone;
    'IonProfile': Components.IonProfile;
    'IonRouter': Components.IonRouter;
    'IonSignup': Components.IonSignup;
    'IonTypes': Components.IonTypes;
    'IonValidationCode': Components.IonValidationCode;
    'IonValidationCompleted': Components.IonValidationCompleted;
    'IonLateralDashboard': Components.IonLateralDashboard;
    'IonCallToAction': Components.IonCallToAction;
    'IonOpenButton': Components.IonOpenButton;
    'IonArrow': Components.IonArrow;
    'IonHeader': Components.IonHeader;
    'IonLogout': Components.IonLogout;
    'IonConfirm': Components.IonConfirm;
    'IonInputRange': Components.IonInputRange;
    'IonMessage': Components.IonMessage;
    'IonNumber': Components.IonNumber;
    'IonSlider': Components.IonSlider;
  }

  interface StencilIntrinsicElements {
    'ion-app': Components.IonAppAttributes;
    'ion-buy': Components.IonBuyAttributes;
    'ion-home': Components.IonHomeAttributes;
    'ion-login': Components.IonLoginAttributes;
    'ion-onboarding-2': Components.IonOnboarding2Attributes;
    'ion-onboarding-3': Components.IonOnboarding3Attributes;
    'ion-onboarding': Components.IonOnboardingAttributes;
    'ion-phone': Components.IonPhoneAttributes;
    'ion-profile': Components.IonProfileAttributes;
    'ion-router': Components.IonRouterAttributes;
    'ion-signup': Components.IonSignupAttributes;
    'ion-types': Components.IonTypesAttributes;
    'ion-validation-code': Components.IonValidationCodeAttributes;
    'ion-validation-completed': Components.IonValidationCompletedAttributes;
    'ion-lateral-dashboard': Components.IonLateralDashboardAttributes;
    'ion-call-to-action': Components.IonCallToActionAttributes;
    'ion-open-button': Components.IonOpenButtonAttributes;
    'ion-arrow': Components.IonArrowAttributes;
    'ion-header': Components.IonHeaderAttributes;
    'ion-logout': Components.IonLogoutAttributes;
    'ion-confirm': Components.IonConfirmAttributes;
    'ion-input-range': Components.IonInputRangeAttributes;
    'ion-message': Components.IonMessageAttributes;
    'ion-number': Components.IonNumberAttributes;
    'ion-slider': Components.IonSliderAttributes;
  }


  interface HTMLIonAppElement extends Components.IonApp, HTMLStencilElement {}
  var HTMLIonAppElement: {
    prototype: HTMLIonAppElement;
    new (): HTMLIonAppElement;
  };

  interface HTMLIonBuyElement extends Components.IonBuy, HTMLStencilElement {}
  var HTMLIonBuyElement: {
    prototype: HTMLIonBuyElement;
    new (): HTMLIonBuyElement;
  };

  interface HTMLIonHomeElement extends Components.IonHome, HTMLStencilElement {}
  var HTMLIonHomeElement: {
    prototype: HTMLIonHomeElement;
    new (): HTMLIonHomeElement;
  };

  interface HTMLIonLoginElement extends Components.IonLogin, HTMLStencilElement {}
  var HTMLIonLoginElement: {
    prototype: HTMLIonLoginElement;
    new (): HTMLIonLoginElement;
  };

  interface HTMLIonOnboarding2Element extends Components.IonOnboarding2, HTMLStencilElement {}
  var HTMLIonOnboarding2Element: {
    prototype: HTMLIonOnboarding2Element;
    new (): HTMLIonOnboarding2Element;
  };

  interface HTMLIonOnboarding3Element extends Components.IonOnboarding3, HTMLStencilElement {}
  var HTMLIonOnboarding3Element: {
    prototype: HTMLIonOnboarding3Element;
    new (): HTMLIonOnboarding3Element;
  };

  interface HTMLIonOnboardingElement extends Components.IonOnboarding, HTMLStencilElement {}
  var HTMLIonOnboardingElement: {
    prototype: HTMLIonOnboardingElement;
    new (): HTMLIonOnboardingElement;
  };

  interface HTMLIonPhoneElement extends Components.IonPhone, HTMLStencilElement {}
  var HTMLIonPhoneElement: {
    prototype: HTMLIonPhoneElement;
    new (): HTMLIonPhoneElement;
  };

  interface HTMLIonProfileElement extends Components.IonProfile, HTMLStencilElement {}
  var HTMLIonProfileElement: {
    prototype: HTMLIonProfileElement;
    new (): HTMLIonProfileElement;
  };

  interface HTMLIonRouterElement extends Components.IonRouter, HTMLStencilElement {}
  var HTMLIonRouterElement: {
    prototype: HTMLIonRouterElement;
    new (): HTMLIonRouterElement;
  };

  interface HTMLIonSignupElement extends Components.IonSignup, HTMLStencilElement {}
  var HTMLIonSignupElement: {
    prototype: HTMLIonSignupElement;
    new (): HTMLIonSignupElement;
  };

  interface HTMLIonTypesElement extends Components.IonTypes, HTMLStencilElement {}
  var HTMLIonTypesElement: {
    prototype: HTMLIonTypesElement;
    new (): HTMLIonTypesElement;
  };

  interface HTMLIonValidationCodeElement extends Components.IonValidationCode, HTMLStencilElement {}
  var HTMLIonValidationCodeElement: {
    prototype: HTMLIonValidationCodeElement;
    new (): HTMLIonValidationCodeElement;
  };

  interface HTMLIonValidationCompletedElement extends Components.IonValidationCompleted, HTMLStencilElement {}
  var HTMLIonValidationCompletedElement: {
    prototype: HTMLIonValidationCompletedElement;
    new (): HTMLIonValidationCompletedElement;
  };

  interface HTMLIonLateralDashboardElement extends Components.IonLateralDashboard, HTMLStencilElement {}
  var HTMLIonLateralDashboardElement: {
    prototype: HTMLIonLateralDashboardElement;
    new (): HTMLIonLateralDashboardElement;
  };

  interface HTMLIonCallToActionElement extends Components.IonCallToAction, HTMLStencilElement {}
  var HTMLIonCallToActionElement: {
    prototype: HTMLIonCallToActionElement;
    new (): HTMLIonCallToActionElement;
  };

  interface HTMLIonOpenButtonElement extends Components.IonOpenButton, HTMLStencilElement {}
  var HTMLIonOpenButtonElement: {
    prototype: HTMLIonOpenButtonElement;
    new (): HTMLIonOpenButtonElement;
  };

  interface HTMLIonArrowElement extends Components.IonArrow, HTMLStencilElement {}
  var HTMLIonArrowElement: {
    prototype: HTMLIonArrowElement;
    new (): HTMLIonArrowElement;
  };

  interface HTMLIonHeaderElement extends Components.IonHeader, HTMLStencilElement {}
  var HTMLIonHeaderElement: {
    prototype: HTMLIonHeaderElement;
    new (): HTMLIonHeaderElement;
  };

  interface HTMLIonLogoutElement extends Components.IonLogout, HTMLStencilElement {}
  var HTMLIonLogoutElement: {
    prototype: HTMLIonLogoutElement;
    new (): HTMLIonLogoutElement;
  };

  interface HTMLIonConfirmElement extends Components.IonConfirm, HTMLStencilElement {}
  var HTMLIonConfirmElement: {
    prototype: HTMLIonConfirmElement;
    new (): HTMLIonConfirmElement;
  };

  interface HTMLIonInputRangeElement extends Components.IonInputRange, HTMLStencilElement {}
  var HTMLIonInputRangeElement: {
    prototype: HTMLIonInputRangeElement;
    new (): HTMLIonInputRangeElement;
  };

  interface HTMLIonMessageElement extends Components.IonMessage, HTMLStencilElement {}
  var HTMLIonMessageElement: {
    prototype: HTMLIonMessageElement;
    new (): HTMLIonMessageElement;
  };

  interface HTMLIonNumberElement extends Components.IonNumber, HTMLStencilElement {}
  var HTMLIonNumberElement: {
    prototype: HTMLIonNumberElement;
    new (): HTMLIonNumberElement;
  };

  interface HTMLIonSliderElement extends Components.IonSlider, HTMLStencilElement {}
  var HTMLIonSliderElement: {
    prototype: HTMLIonSliderElement;
    new (): HTMLIonSliderElement;
  };

  interface HTMLElementTagNameMap {
    'ion-app': HTMLIonAppElement
    'ion-buy': HTMLIonBuyElement
    'ion-home': HTMLIonHomeElement
    'ion-login': HTMLIonLoginElement
    'ion-onboarding-2': HTMLIonOnboarding2Element
    'ion-onboarding-3': HTMLIonOnboarding3Element
    'ion-onboarding': HTMLIonOnboardingElement
    'ion-phone': HTMLIonPhoneElement
    'ion-profile': HTMLIonProfileElement
    'ion-router': HTMLIonRouterElement
    'ion-signup': HTMLIonSignupElement
    'ion-types': HTMLIonTypesElement
    'ion-validation-code': HTMLIonValidationCodeElement
    'ion-validation-completed': HTMLIonValidationCompletedElement
    'ion-lateral-dashboard': HTMLIonLateralDashboardElement
    'ion-call-to-action': HTMLIonCallToActionElement
    'ion-open-button': HTMLIonOpenButtonElement
    'ion-arrow': HTMLIonArrowElement
    'ion-header': HTMLIonHeaderElement
    'ion-logout': HTMLIonLogoutElement
    'ion-confirm': HTMLIonConfirmElement
    'ion-input-range': HTMLIonInputRangeElement
    'ion-message': HTMLIonMessageElement
    'ion-number': HTMLIonNumberElement
    'ion-slider': HTMLIonSliderElement
  }

  interface ElementTagNameMap {
    'ion-app': HTMLIonAppElement;
    'ion-buy': HTMLIonBuyElement;
    'ion-home': HTMLIonHomeElement;
    'ion-login': HTMLIonLoginElement;
    'ion-onboarding-2': HTMLIonOnboarding2Element;
    'ion-onboarding-3': HTMLIonOnboarding3Element;
    'ion-onboarding': HTMLIonOnboardingElement;
    'ion-phone': HTMLIonPhoneElement;
    'ion-profile': HTMLIonProfileElement;
    'ion-router': HTMLIonRouterElement;
    'ion-signup': HTMLIonSignupElement;
    'ion-types': HTMLIonTypesElement;
    'ion-validation-code': HTMLIonValidationCodeElement;
    'ion-validation-completed': HTMLIonValidationCompletedElement;
    'ion-lateral-dashboard': HTMLIonLateralDashboardElement;
    'ion-call-to-action': HTMLIonCallToActionElement;
    'ion-open-button': HTMLIonOpenButtonElement;
    'ion-arrow': HTMLIonArrowElement;
    'ion-header': HTMLIonHeaderElement;
    'ion-logout': HTMLIonLogoutElement;
    'ion-confirm': HTMLIonConfirmElement;
    'ion-input-range': HTMLIonInputRangeElement;
    'ion-message': HTMLIonMessageElement;
    'ion-number': HTMLIonNumberElement;
    'ion-slider': HTMLIonSliderElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
